/**
 * Human-readable Brazilian Portuguese labels for every `NiceFuncType` enum
 * value returned by Atlas Academy's `/nice` API. Used as a fallback when a
 * `NiceFunction.funcPopupText` is empty or in another language.
 *
 * Source: https://api.atlasacademy.io/openapi.json -> NiceFuncType enum.
 * Translated and grouped so the UI can show a meaningful chip even when
 * Atlas doesn't ship a localised popup text for a given function.
 */
export const FUNC_TYPE_LABELS: Readonly<Record<string, string>> = Object.freeze(
  {
    none: 'Sem efeito',
    addState: 'Aplicar estado',
    subState: 'Remover estado',
    damage: 'Causar dano',
    damageNp: 'Causar dano de NP',
    gainStar: 'Gerar estrelas',
    gainHp: 'Recuperar HP',
    gainNp: 'Ganho de NP',
    lossNp: 'Perda de NP',
    shortenSkill: 'Reduzir recarga',
    extendSkill: 'Aumentar recarga',
    releaseState: 'Remover status',
    lossHp: 'Perder HP',
    instantDeath: 'Morte instantânea',
    damageNpPierce: 'Dano NP perfurante',
    damageNpIndividual: 'Dano NP individual',
    addStateShort: 'Aplicar estado (curto)',
    gainHpPer: 'Recuperar HP (% máx)',
    damageNpStateIndividual: 'Dano NP vs estado',
    hastenNpturn: 'Acelerar turno de NP',
    delayNpturn: 'Adiar turno de NP',
    damageNpHpratioHigh: 'Dano NP (HP alto)',
    damageNpHpratioLow: 'Dano NP (HP baixo)',
    cardReset: 'Resetar cartas',
    replaceMember: 'Trocar membro',
    lossHpSafe: 'Perder HP (seguro)',
    damageNpCounter: 'Dano NP (contra-ataque)',
    damageNpStateIndividualFix: 'Dano NP fixo vs estado',
    damageNpSafe: 'Dano NP (seguro)',
    callServant: 'Convocar servo',
    ptShuffle: 'Embaralhar time',
    lossStar: 'Perder estrelas',
    changeServant: 'Trocar servo',
    changeBg: 'Mudar cenário',
    damageValue: 'Causar dano fixo',
    withdraw: 'Recuar',
    fixCommandcard: 'Fixar carta',
    shortenBuffturn: 'Reduzir duração',
    extendBuffturn: 'Estender duração',
    shortenBuffcount: 'Reduzir cargas',
    extendBuffcount: 'Aumentar cargas',
    changeBgm: 'Trocar BGM',
    displayBuffstring: 'Mostrar mensagem',
    resurrection: 'Ressurreição',
    gainNpBuffIndividualSum: 'Ganho NP (soma de buffs)',
    setSystemAliveFlag: 'Sinalizar vivo',
    forceInstantDeath: 'Forçar morte instantânea',
    damageNpRare: 'Dano NP vs raro',
    gainNpFromTargets: 'Ganho NP dos alvos',
    gainHpFromTargets: 'HP dos alvos',
    lossHpPer: 'Perder HP (% atual)',
    lossHpPerSafe: 'Perder HP (% seguro)',
    shortenUserEquipSkill: 'Reduzir recarga equipada',
    quickChangeBg: 'Troca rápida de cenário',
    shiftServant: 'Reposicionar servo',
    damageNpAndOrCheckIndividuality: 'Dano NP vs individuality',
    absorbNpturn: 'Absorver turno de NP',
    overwriteDeadType: 'Sobrescrever tipo de morte',
    forceAllBuffNoact: 'Forçar buffs sem ação',
    breakGaugeUp: 'Aumentar Break Gauge',
    breakGaugeDown: 'Reduzir Break Gauge',
    moveToLastSubmember: 'Mover para reserva',
    extendUserEquipSkill: 'Estender recarga equipada',
    updateEnemyEntryMaxCountEachTurn: 'Limitar entrada de inimigos',
    expUp: 'Bônus de EXP',
    qpUp: 'Bônus de QP',
    dropUp: 'Bônus de drop',
    friendPointUp: 'Bônus de Friend Point',
    eventDropUp: 'Drop de evento up',
    eventDropRateUp: 'Taxa de drop de evento up',
    eventPointUp: 'Pontos de evento up',
    eventPointRateUp: 'Taxa de pontos de evento up',
    transformServant: 'Transformar servo',
    qpDropUp: 'Drop de QP up',
    servantFriendshipUp: 'Bônus de Bond',
    userEquipExpUp: 'EXP de equipamento up',
    classDropUp: 'Drop de classe up',
    enemyEncountCopyRateUp: 'Taxa de cópia de encontro',
    enemyEncountRateUp: 'Taxa de encontro',
    enemyProbDown: 'Chance de inimigo reduzida',
    getRewardGift: 'Obter recompensa',
    sendSupportFriendPoint: 'Enviar FP ao suporte',
    movePosition: 'Mover posição',
    revival: 'Reviver',
    damageNpIndividualSum: 'Dano NP individual (soma)',
    damageValueSafe: 'Dano fixo (seguro)',
    friendPointUpDuplicate: 'Bônus de FP (extra)',
    moveState: 'Mover estado',
    changeBgmCostume: 'Trocar BGM (traje)',
    lossCommandSpell: 'Perder Command Spell',
    gainCommandSpell: 'Ganhar Command Spell',
    updateEntryPositions: 'Atualizar posições',
    buddyPointUp: 'Bônus de Buddy Point',
    addFieldChangeToField: 'Adicionar mudança ao campo',
    subFieldBuff: 'Remover buff de campo',
    eventFortificationPointUp: 'Pontos de fortificação up',
    gainNpIndividualSum: 'Ganho NP individual (soma)',
    setQuestRouteFlag: 'Marcar rota de quest',
    lastUsePlayerSkillCopy: 'Copiar última skill do jogador',
    changeEnemyMasterFace: 'Trocar rosto do mestre inimigo',
    damageValueSafeOnce: 'Dano fixo (1 vez)',
    addBattleValue: 'Adicionar valor de batalha',
    setBattleValue: 'Definir valor de batalha',
    gainMultiplyNp: 'Ganho de NP (multiplicador)',
    lossMultiplyNp: 'Perda de NP (multiplicador)',
    addBattlePoint: 'Adicionar Battle Point',
    damageNpBattlePointPhase: 'Dano NP por fase de BP',
    setNpExecutedState: 'Marcar NP como usado',
    hideOverGauge: 'Esconder Over Gauge',
    gainNpTargetSum: 'Ganho NP (soma alvos)',
    enemyCountChange: 'Mudar contagem de inimigos',
    displayBattleMessage: 'Mostrar mensagem de batalha',
    generateBattleSkillDrop: 'Gerar drop de skill',
    changeMasterFace: 'Trocar rosto do mestre',
    enableMasterSkill: 'Habilitar skill de mestre',
    enableMasterCommandSpell: 'Habilitar Command Spell',
    battleModelChange: 'Trocar modelo de batalha',
    gainNpCriticalstarSum: 'Ganho NP (estrelas)',
    addBattleMissionValue: 'Adicionar valor de missão',
    setBattleMissionValue: 'Definir valor de missão',
    changeEnemyStatusUiType: 'Trocar UI de status',
    swapFieldPosition: 'Trocar posições de campo',
    setDisplayDirectBattleMessageInFsm: 'Mensagem direta em FSM',
    addStateToField: 'Aplicar estado no campo',
    addStateShortToField: 'Aplicar estado (curto) no campo',
    gainNpFromOtherUsedNpValue: 'Ganho NP de NP usado',
    hastenNpturnFromOtherUsedNpturn: 'Acelerar turno de NP usado',
    damageFuncType164: 'Dano NP (tipo 164)',
    damageFuncType165: 'Dano NP (tipo 165)',
    subBattlePoint: 'Remover Battle Point',
    setBattleMissionValueAsMax: 'Definir missão como máximo',
    addStateFuncType169: 'Aplicar estado (tipo 169)',
    addStateFuncType170: 'Aplicar estado (tipo 170)',
  }
);

/** Skill target type labels (PT-BR) — see `NiceFuncTargetType`. */
export const FUNC_TARGET_TYPE_LABELS: Readonly<Record<string, string>> =
  Object.freeze({
    self: 'Si mesmo',
    ptOne: '1 aliado',
    ptAnother: 'Outro aliado',
    ptAll: 'Todos aliados',
    enemy: '1 inimigo',
    enemyAnother: 'Outro inimigo',
    enemyAll: 'Todos inimigos',
    ptFull: 'Time + reserva',
    enemyFull: 'Inimigos + reserva',
    ptOther: 'Outros aliados',
    ptOneOther: 'Outro aliado (1)',
    ptRandom: 'Aliado aleatório',
    enemyOther: 'Outros inimigos',
    enemyRandom: 'Inimigo aleatório',
    ptOtherFull: 'Outros aliados + reserva',
    enemyOtherFull: 'Outros inimigos + reserva',
    ptselectOneSub: 'Escolher 1 da reserva',
    ptselectSub: 'Escolher da reserva',
    ptOneAnotherRandom: 'Outro aliado aleatório',
    ptSelfAnotherRandom: 'Outro si mesmo aleatório',
    enemyOneAnotherRandom: 'Outro inimigo aleatório',
    ptSelfAnotherFirst: 'Próximo aliado à direita',
    ptSelfBefore: 'Aliado à esquerda',
    ptSelfAfter: 'Aliado à direita',
    ptSelfAnotherLast: 'Último aliado',
    commandTypeSelfTreasureDevice: 'Si mesmo (NP)',
    fieldOther: 'Outro do campo',
    enemyOneNoTargetNoAction: 'Inimigo (sem alvo)',
    ptOneHpLowestValue: 'Aliado (menor HP)',
    ptOneHpLowestRate: 'Aliado (menor % HP)',
    enemyRange: 'Alcance inimigo',
    handCommandcardRandomOne: 'Carta aleatória da mão',
    fieldAll: 'Todo o campo',
    noTarget: 'Sem alvo',
    fieldRandom: 'Campo aleatório',
    playerAttackPreselectTargetPtOne: 'Alvo pré-selecionado',
  });

/** Function apply target (team) labels. */
export const FUNC_APPLY_TARGET_LABELS: Readonly<Record<string, string>> =
  Object.freeze({
    player: 'aliados',
    enemy: 'inimigos',
    playerAndEnemy: 'aliados e inimigos',
  });
